version: '3.8'

services:
  # XY Stock Web 应用服务 - 开发模式
  xystock-web:
    #build: .
    image: xieyan800811/xystock:latest
    container_name: xystock-web
    ports:
      - "8811:8811"
    volumes:
      # 整个项目目录映射到容器 - 便于开发调试
      - .:/app
    environment:
      # 设置时区
      - TZ=Asia/Shanghai
      # Python相关环境变量
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      # Streamlit配置
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8811
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    # 开发模式：保持容器运行但不自动启动应用
    tty: true
    stdin_open: true
    command: /bin/bash  # 覆盖 Dockerfile 中的 CMD，启动为交互式 bash
    restart: unless-stopped
    networks:
      - xystock-network

networks:
  xystock-network:
    driver: bridge

